project_id = "wjrcutrjltukskwicjnx"

[functions.audit-start]
verify_jwt = true

[functions.audit-status]
verify_jwt = true

[functions.audit-cancel]
verify_jwt = true

[functions.optimization-calculate]
verify_jwt = true

[functions.send-email]
verify_jwt = true
