project_id = "dllusofuxonaemrttmwl"

[functions.audit-start]
verify_jwt = false

[functions.audit-status]
verify_jwt = false

[functions.audit-cancel]
verify_jwt = true

[functions.audit-processor]
verify_jwt = false

[functions.optimization-content]
verify_jwt = true

[functions.optimization-processor]
verify_jwt = true

[functions.optimization-start]
verify_jwt = true

[functions.optimization-status]
verify_jwt = true
